---
# .github/workflows/docker-pipeline.yml

name: Docker build

on: push

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
