---
# .github/workflows/gh-release.yml

name: GH Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: GH Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
